# Generated by Django 4.0.2 on 2022-10-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maanage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='empid',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='maanage.address'),
        ),
    ]
