# Generated by Django 4.0.2 on 2022-10-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maanage', '0003_remove_employee_address_address_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maanage.employee'),
        ),
    ]
