# Generated by Django 4.0.2 on 2022-10-08 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maanage', '0005_employee_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='maanage.employee'),
        ),
    ]
