# Generated by Django 4.0.2 on 2022-10-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maanage', '0006_alter_address_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='addr',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
